# Default values for main-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: default
image:
  repository: fbksense/response-router
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0"

loglevel: "DEBUG"
loggername: " Response Router "
apiport: "3000"

service:
  type: NodePort
  port: 3000
  #nodeport: 32300
  protocol: TCP
nodePort: 32300

msgbrokerep: "80.159.227.43:31123"
msgbrokeruser: ""
msgbrokerpwd: ""
sendtopic: "TO_CARS"
